#!/bin/sh
### BEGIN INIT INFO
# Provides:          firstboot
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Inital XTC Setup
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting firstboot"
    /opt/thinclient/install/firstboot.sh &&
    update-rc.d firstboot remove &&
    rm /etc/init.d/firstboot &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
